/**
 * data.ts — data sources for the pi-king dashboard banner,
 * stats line, inventory block, and landing page.
 *
 * Kept separate from pi-dashboard.ts so the rendering code stays readable and
 * so each source's cost and failure mode is documented next to the code that
 * pays it. Every source here is local-only: no network, no daemon, no auth.
 *
 * Deliberately NOT sourced here:
 *  - Skill/prompt invocation counts. Pi's session JSONL format records no
 *    skill-invocation entry (verified against all 101 session files: entry
 *    types are only message / custom / model_change / session / session_info /
 *    thinking_level_change, and skills expand inline into user message text
 *    leaving no structured marker). Deriving counts would mean fuzzy string
 *    matching across multi-MB transcripts — unreliable and slow. Inventory is
 *    therefore sorted alphabetically, not by usage.
 *  - Cost. call_logs carries no price data; a hardcoded price table would rot
 *    silently. A fabricated authoritative-looking number is worse than none.
 */

import { openSync, readSync, closeSync, readdirSync, readFileSync, statSync } from "node:fs";
import { readdir, readFile } from "node:fs/promises";
import { join, basename } from "node:path";
import { homedir } from "node:os";

const HOME = homedir();
/** Inventory reflects the configuration actually in force, so it must follow
 * PI_CODING_AGENT_DIR rather than assume the default location. */
const AGENT_DIR = process.env.PI_CODING_AGENT_DIR?.trim() || join(HOME, ".pi", "agent");

/** Directory of per-day call-log JSON, if one exists on this machine.
 *
 * Deliberately has no default. The metrics band reads a log format produced by
 * a router sitting in front of the model providers, and there is no format any
 * stock Pi install writes. Hardcoding one vendor's path would name a specific
 * third-party tool in a general-purpose package and would show nothing for
 * everyone who does not run it. Unset means the band is simply absent, which
 * matches the rule that missing data renders as nothing. See README. */
const CALL_LOGS = process.env.PI_KING_CALL_LOGS?.trim() || undefined;

/* ------------------------------------------------------------------ art -- */

/**
 * The π wordmark, pre-rendered as Braille (U+2800) art.
 *
 * Braille packs a 2x4 subpixel grid into a single character cell, giving 8x
 * the effective resolution of block-drawing characters — which is why this
 * reads as a real glyph rather than a blocky approximation.
 *
 * Generated by ~/.pi/agent/tools/pi-braille-art.py: the serif `π` (Times, whose
 * curved entry and flared leg read far better than a geometric sans at this
 * density) with a viking helmet — dome, brow band, and swept horns — drawn as
 * vectors over it, then mapped 2x4 pixels to Braille codepoints. The mark is
 * the name: pi-king. It is
 * committed as a constant rather than generated at runtime because the glyph
 * never changes, and shelling out to Python on every dashboard open would be a
 * pointless cost. Re-run the generator to resize.
 */
export const PI_ART: readonly string[] = [
  "\u28a6\u2840\u2800\u2800\u2800\u28c0\u2800\u2800\u2800\u2880\u2874",
  "\u2808\u28b7\u28c4\u28f4\u28ff\u28ff\u28ff\u28e6\u28e0\u287e\u2801",
  "\u2800\u28e8\u28ff\u28ff\u28ff\u28ff\u28ff\u28ff\u28ff\u28c5",
  "\u2800\u2809\u28b9\u28ff\u2809\u2809\u2809\u28ff\u284f\u2809",
  "\u2800\u2800\u28b8\u28ff\u2800\u2800\u2800\u28ff\u2847",
  "\u2800\u2800\u2818\u281b\u2800\u2800\u2800\u281b\u281b\u2802",
];

/* ------------------------------------------------------------ inventory -- */

export type Inventory = {
  skills: string[];
  prompts: string[];
  extensions: string[];
  clis: string[];
};

/** CLIs worth reporting presence of — variable across machines and not printed
 * anywhere else, unlike skills/prompts which Pi lists at startup. Kept to
 * widely-used developer tools; override with PI_KING_CLIS (comma-separated) to
 * track your own. Listing someone's private tooling by default would leak the
 * shape of their setup into any screenshot they share. */
const CLI_CANDIDATES = process.env.PI_KING_CLIS?.trim()
  ? process.env.PI_KING_CLIS.split(",").map((c) => c.trim()).filter(Boolean)
  : ["bat", "docker", "fd", "gh", "jq", "rg", "tmux"];

function listDir(path: string, pick: (entry: string, full: string) => string | undefined): string[] {
  try {
    return readdirSync(path)
      .map((e) => pick(e, join(path, e)))
      .filter((v): v is string => Boolean(v))
      .sort();
  } catch {
    return [];
  }
}

function onPath(cmd: string): boolean {
  const dirs = (process.env.PATH ?? "").split(":").filter(Boolean);
  for (const d of dirs) {
    try {
      statSync(join(d, cmd));
      return true;
    } catch {
      // not here; keep looking
    }
  }
  return false;
}

/**
 * Snapshot of what's installed. Called once when the dashboard opens — this is
 * static between config edits, so there is no refresh and no TTL.
 * Measured at ~0.1s in Python, dominated by interpreter startup; here it is a
 * handful of readdir/stat calls.
 */
export function readInventory(): Inventory {
  return {
    skills: listDir(join(AGENT_DIR, "skills"), (e, full) => {
      try {
        statSync(join(full, "SKILL.md"));
        return e;
      } catch {
        return undefined;
      }
    }),
    prompts: listDir(join(AGENT_DIR, "prompts"), (e) => (e.endsWith(".md") ? e.replace(/\.md$/, "") : undefined)),
    extensions: listDir(join(AGENT_DIR, "extensions"), (e) => (e.endsWith(".ts") ? e.replace(/\.ts$/, "") : undefined)),
    clis: CLI_CANDIDATES.filter(onPath),
  };
}

/* ---------------------------------------------------------------- stats -- */

export type UsageStats = {
  calls: number;
  errors: number;
  topModels: Array<{ model: string; pct: number }>;
  /** Calls per hour, midnight through the current hour. Real data from each
   * call's own timestamp — not smoothed, not synthesised. */
  hourly: number[];
  peakHour: number;
  partial: boolean;
};

function today(): string {
  const d = new Date();
  const p = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

/** Strips vendor/route prefixes so model names fit the one-line ticker. */
function shortModel(id: string): string {
  return id.replace(/^omni-/, "").replace(/^(anthropic|openai|codex|claude)\//, "");
}

/**
 * Aggregates today's call logs from the directory named by PI_KING_CALL_LOGS.
 *
 * Cost is real: ~2,100 files for a busy day, measured at ~0.5s. That is far
 * too slow for the dashboard's 1s render tick, so this is async and callers
 * must cache it (see StatsCache) rather than awaiting it on the render path.
 *
 * Returns undefined when no log directory is configured, or when today's
 * directory does not exist — meaning no calls were routed today. Callers must
 * render nothing rather than "0 calls", which would falsely imply measured
 * inactivity rather than absent measurement.
 */
export async function readUsageStats(): Promise<UsageStats | undefined> {
  if (!CALL_LOGS) return undefined;
  const dir = join(CALL_LOGS, today());
  let files: string[];
  try {
    files = (await readdir(dir)).filter((f) => f.endsWith(".json"));
  } catch {
    return undefined;
  }
  if (files.length === 0) return undefined;

  const counts = new Map<string, number>();
  const byHour = new Map<number, number>();
  let calls = 0;
  let errors = 0;
  let partial = false;

  // Bounded concurrency: unbounded Promise.all over thousands of files spikes
  // file descriptors for no throughput gain.
  const BATCH = 64;
  for (let i = 0; i < files.length; i += BATCH) {
    const batch = files.slice(i, i + BATCH);
    const results = await Promise.all(batch.map(async (f) => {
      try {
        return JSON.parse(await readFile(join(dir, f), "utf8")) as { summary?: Record<string, unknown> };
      } catch {
        return undefined;
      }
    }));
    for (const r of results) {
      const s = r?.summary;
      if (!s) {
        partial = true;
        continue;
      }
      calls++;
      const status = typeof s.status === "number" ? s.status : 0;
      if (status >= 400) errors++;
      const model = shortModel(String(s.model ?? "unknown"));
      counts.set(model, (counts.get(model) ?? 0) + 1);
      // Timestamps are ISO-8601 UTC; hour lives at offset 11..13.
      const ts = typeof s.timestamp === "string" ? s.timestamp : "";
      if (ts.length >= 13) {
        const h = Number(ts.slice(11, 13));
        if (Number.isFinite(h)) byHour.set(h, (byHour.get(h) ?? 0) + 1);
      }
    }
  }
  if (calls === 0) return undefined;

  const topModels = [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([model, n]) => ({ model, pct: Math.round((n / calls) * 100) }));

  const lastHour = byHour.size > 0 ? Math.max(...byHour.keys()) : 0;
  const hourly: number[] = [];
  for (let h = 0; h <= lastHour; h++) hourly.push(byHour.get(h) ?? 0);

  return { calls, errors, topModels, hourly, peakHour: Math.max(0, ...hourly), partial };
}

/**
 * Lazily-refreshed cache with a 60s TTL. Reads never block: callers get the
 * previous value (or undefined on first paint) and a refresh is kicked off in
 * the background, so the dashboard is navigable immediately on open.
 */
export const STATS_TTL_MS = 60_000;

class StatsCache {
  private value: UsageStats | undefined;
  private loaded = false;
  private fetchedAt = 0;
  private inFlight = false;

  constructor(private onUpdate: () => void) {}

  /** Non-blocking. Triggers a background refresh when stale. */
  get(): { stats: UsageStats | undefined; loaded: boolean } {
    if (!this.inFlight && Date.now() - this.fetchedAt > STATS_TTL_MS) {
      this.inFlight = true;
      readUsageStats()
        .then((s) => { this.value = s; })
        .catch(() => { this.value = undefined; })
        .finally(() => {
          this.loaded = true;
          this.fetchedAt = Date.now();
          this.inFlight = false;
          this.onUpdate();
        });
    }
    return { stats: this.value, loaded: this.loaded };
  }
}

/* ------------------------------------------------------ recent projects -- */

export type RecentProject = { project: string; path: string; lastActive: number };

/** Reads just the first line of a file without slurping it. Session
 * transcripts reach multi-MB; only the opening `session` entry is needed. */
function firstLine(path: string, max = 512): string {
  let fd: number | undefined;
  try {
    fd = openSync(path, "r");
    const buf = Buffer.alloc(max);
    const n = readSync(fd, buf, 0, max, 0);
    const text = buf.subarray(0, n).toString("utf8");
    const nl = text.indexOf("\n");
    return nl === -1 ? text : text.slice(0, nl);
  } catch {
    return "";
  } finally {
    if (fd !== undefined) {
      try { closeSync(fd); } catch { /* already gone */ }
    }
  }
}

/**
 * Recent project directories, newest first, for the landing page when no
 * sessions are running — so an empty dashboard offers a way back into work
 * instead of just saying "nothing here".
 *
 * The real cwd is read from the opening `session` entry of the newest
 * transcript, NOT decoded from the session directory name. That encoding
 * (`--Users-you-codebase-example-project--`) is genuinely ambiguous: a literal
 * hyphen in a directory name is indistinguishable from a path separator, so
 * naive decoding turns `codebase/example-project` into `codebase/example/project`.
 * Confirmed against a real session before choosing this approach.
 *
 * Cost stays low: one readdir per project dir plus a 512-byte read of one
 * file. Transcripts are never parsed.
 */
export function readRecentProjects(limit = 5): RecentProject[] {
  const root = join(AGENT_DIR, "sessions");
  let entries: string[];
  try {
    entries = readdirSync(root);
  } catch {
    return [];
  }

  const dirs: Array<{ dir: string; lastActive: number }> = [];
  for (const e of entries) {
    try {
      const st = statSync(join(root, e));
      if (st.isDirectory()) dirs.push({ dir: e, lastActive: st.mtimeMs });
    } catch {
      // vanished between readdir and stat; skip
    }
  }
  dirs.sort((a, b) => b.lastActive - a.lastActive);

  const out: RecentProject[] = [];
  for (const { dir, lastActive } of dirs) {
    if (out.length >= limit) break;
    const full = join(root, dir);
    let newest: { file: string; mtime: number } | undefined;
    try {
      for (const f of readdirSync(full)) {
        if (!f.endsWith(".jsonl")) continue;
        const mt = statSync(join(full, f)).mtimeMs;
        if (!newest || mt > newest.mtime) newest = { file: f, mtime: mt };
      }
    } catch {
      continue;
    }
    if (!newest) continue;
    let cwd = "";
    try {
      const parsed = JSON.parse(firstLine(join(full, newest.file))) as { cwd?: unknown };
      if (typeof parsed.cwd === "string") cwd = parsed.cwd;
    } catch {
      // Unparseable opening entry — skip rather than show a guessed path.
      continue;
    }
    if (!cwd) continue;
    out.push({ project: basename(cwd) || cwd, path: cwd, lastActive });
  }
  return out;
}

/** Unicode block sparkline. Returns "" for empty input rather than a fake
 * flat line, so "no data" never renders as "measured zero". */
export function sparkline(series: number[]): string {
  if (series.length === 0) return "";
  const blocks = "\u2581\u2582\u2583\u2584\u2585\u2586\u2587\u2588";
  const max = Math.max(...series);
  if (max <= 0) return "";
  return series.map((v) => blocks[Math.min(7, Math.floor((v / max) * 7))]).join("");
}

/* ---------------------------------------------------------------- quote -- */

/**
 * Quote of the day.
 *
 * Deliberately NOT fetched from a network API: this renders on dashboard open,
 * and a remote call there would add latency, an offline failure mode, and a
 * dependency — for a decorative line. A local list rotating on the date gives
 * the identical experience with none of that, and works on a plane.
 *
 * Users can override with their own one-per-line file (blank lines and
 * `#` comments ignored) at $PI_CODING_AGENT_DIR/pi-king-quotes.txt.
 */
const QUOTES: readonly string[] = [
  "Not all who wander are lost. Some are just detached.",
  "Uneasy lies the head that wears the helmet.",
  "A king is only as good as his subjects \u2014 and yours are all idle.",
  "\u03c0 is irrational. So is running nine sessions at once.",
  "Conquer. Pillage. Detach.",
  "The horns are decorative. The persistence is not.",
  "A watched session never compacts.",
  "He who controls the tmux controls the universe.",
  "Ragnar\u00f6k is just a very large refactor.",
  "In Valhalla, all tests pass.",
  "Long live the king \u2014 and the session you left running since Tuesday.",
  "Some sessions are born great. Some achieve greatness. Some just never got killed.",
  "Sharpen the axe, then run the tests.",
  "A fleet is just loneliness, in parallel.",
  "3.14159 reasons to background that session.",
  "Your subjects are working. You are watching. Both are billable.",
  "Idle hands are the compiler's workshop.",
  "Two roads diverged in a wood, and I took the one with tmux.",
  "Rule kindly. Or at least remember they exist.",
  "The raiding party returns when it returns.",
  "Every kingdom falls. Yours falls to an unhandled promise rejection.",
  "\u03c0-rate: the speed at which you plunder your token budget.",
  "Detachment is not indifference.",
  "Winter is coming. So is the context limit.",
  "A crown is just a helmet that stopped doing its job.",

  // \u2014 norse
  "Odin gave an eye for wisdom. You gave a context window.",
  "The longship sails whether or not you watch it.",
  "Berserkers never asked permission either.",
  "Sk\u00e5l to the sessions that survived the night.",
  "A saga is just a very long changelog.",
  "Raid. Loot. Detach. Repeat.",
  "Valhalla has no merge conflicts.",
  "Runes were also just poorly documented syntax.",
  "Longships were the original horizontal scaling.",
  "Thor had a hammer. You have a rollback.",
  "The raven brings news. Usually a stack trace.",

  // \u2014 crown
  "Heavy is the head that runs nine agents.",
  "The king is dead. Long live the daemon.",
  "Et tu, linter?",
  "A horse, a horse, my kingdom for a green test suite.",
  "All the terminal's a stage, and all the sessions merely players.",
  "Something is rotten in the state of node_modules.",
  "To compact, or not to compact.",
  "Crowns are heavy. Delegate.",
  "A kingdom divided cannot ship.",
  "Kings do not read logs. Kings are told about logs.",

  // \u2014 \u03c0
  "\u03c0 goes on forever. So does this refactor.",
  "Irrational, transcendental, and still more predictable than an LLM.",
  "You can approximate \u03c0. You cannot approximate a passing test.",
  "Circumference of scope creep: unbounded.",
  "Some constants are universal. Your build time is not one of them.",

  // \u2014 terminal
  "Detached, not deserted.",
  "It works on my session.",
  "The session persists. The motivation does not.",
  "There is no cloud, only someone else's tmux.",
  "Ctrl+C is not a strategy.",
  "Your terminal has more tabs than your browser. Seek counsel.",
  "The best time to background a session was an hour ago.",
  "git blame, then git blame yourself.",

  // \u2014 agents
  "The agent is thinking. Allegedly.",
  "Six agents, one bottleneck: you.",
  "Autonomy is delegation with better marketing.",
  "The subagent finished. Nobody was watching.",
  "It is not hallucinating, it is improvising.",
  "Trust, but verify. Mostly verify.",
  "Parallel agents, serial regrets.",
  "Somewhere, a session you forgot is still working.",
  "Persistence is the only feature that matters at 3am.",
  "You will come back. They always do.",
];

/** Day-of-year rotation: stable for a whole day, no randomness, no state. */
export function quoteOfTheDay(): string {
  let pool: string[] = [...QUOTES];
  try {
    const custom = readFileSync(join(AGENT_DIR, "pi-king-quotes.txt"), "utf8")
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l && !l.startsWith("#"));
    if (custom.length > 0) pool = custom;
  } catch {
    // No override file — the built-in list is the default, not a fallback.
  }
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const day = Math.floor((now.getTime() - start.getTime()) / 86_400_000);
  return pool[day % pool.length] ?? pool[0];
}
